### ISSUE TITLE
Explicit permissions in docs

### ISSUE THREAD

**Issue by jollytoad** [Hexagon/deps#1]
One of the big advantages of Deno is it's secure by default permission model. It would be really helpful to give explicit permission flags in the docs as an alternative to the blanket `-A`.

I found I could just provide the following options...

```
deno run --allow-read=. --allow-net=jsr.io,registry.npmjs.org jsr:@check/deps
```

Ideally it would be good to just supply `--allow-read=deno.json,deno.lock` and have it ignore lack of permission for alternative `deno.jsonc` for example.

(Sorry, I should add that this is a fantasic little tool btw, exactly what I've been missing, thank you very much for this)

**Comment by Hexagon** [comment]
I'll have a look at this :+1:

**Comment by Hexagon** [comment]
@jollytoad https://github.com/Hexagon/deps/releases/tag/0.3.3
