### ISSUE TITLE
Suggestion: Pre-release status

### ISSUE THREAD

**Issue by jollytoad** [Hexagon/deps#2]
If you are currently using a pre-release version of a JSR module, it appears to show as `Outdated`...

![Screenshot 2024-06-21 at 11 59 16 AM](https://github.com/Hexagon/deps/assets/71291/8d31b0de-f569-4ffc-93db-e93e7ea4b1da)

Everytime I run this and see this item as outdated, I have a double-take moment and then realise it's actually a
pre-release rather than outdated.

I think it would be helpful to display something like `Pre-release` instead to reduce cognitive overhead, and maybe
highlight it in an alternative colour, yellow/orange/cyan?

**Comment by Hexagon** [comment]
I agree, will have a look when i find some time! I guess showing pre-release in yellow would be the most intuitive.

**Comment by Hexagon** [comment]
Should be fixed through https://github.com/Hexagon/deps/releases/tag/0.4.0

**Comment by jollytoad** [comment]
Fantastic, thank you, works great.
