### ISSUE TITLE
Suggestion: Include pre-releases as latest

### ISSUE THREAD

**Issue by jollytoad** [Hexagon/deps#3]
I'm trying to test out the latest pre-releases of `@std` packages, it would be really useful if `@check/deps` had a flag to allow the `Latest` to include these pre-release versions too, so I know what is now available for testing.

**Comment by Hexagon** [comment]
I agree, will have a look!

**Comment by Hexagon** [comment]
Not sure this is needed since pre-releases is treated as valid since https://github.com/Hexagon/deps/releases/tag/0.4.0 , try it out and see what you think!

**Comment by jollytoad** [comment]
So this is different to showing the status, take this for example...

![Screenshot 2024-06-24 at 9 01 42 AM](https://github.com/Hexagon/deps/assets/71291/b8c15d2b-1852-47f0-8ae3-43d1d249add9)

`@std/assert` shows the `Latest` as `0.226.0`, but there is currently `1.0.0-rc.2` release available, so the behaviour I'm suggesting would be a flag (`--pre-release` maybe?) to show this `1.0.0-rc.2` version instead in the `Latest` column (or maybe an additional `Pre-release` column, with or without the flag).

**Comment by Hexagon** [comment]
Now i see, great suggestion! Please try out `0.5.2` and see how that works for you (--pre-release is added, always demanding the latest pre-release version. It does also change the yellow label to green if using a pre-release version.).

Now, in detail;
- if you have a pre-release version installed, but not supply `--pre-release`, "Up-to-date (Pre-release)" is shown in yellow.
- the same scenario with `--pre-release` supplied shows "Up-to-date" in green.
- If you are using the latest wanted version without `--pre-release`, green "Up-to-date" is (of course) shown
- If you are using a version, but supply `--pre-release`, and there is a later pre-release available, "Outdated" is shown in red.

**Comment by jollytoad** [comment]
Ah, you absolute legend, that is spot on, works a treat, thank you very much. 🥇
