### ISSUE TITLE
Show version used in deno.lock

### ISSUE THREAD

**Issue by eturino** [Hexagon/deps#4]
I'd like to see not only the difference between what it is Wanted in deno.json but also what it is actually used in the deno.lock. That way I could get better warning of when some dependency should change in the app, when I need to refresh the lock to get latest versions, etc.

Similar to how yarn outdated worked in classic

https://classic.yarnpkg.com/lang/en/docs/cli/outdated/

```
Package    Current Wanted Latest
lodash     4.15.0  4.15.0 4.16.4
underscore 1.6.0   1.6.1  1.8.3
```

**Comment by Hexagon** [comment]
Fixed in `0.7.4`
